import type { Metadata } from "next";
import localFont from "next/font/local";
import { CommonsLayout } from "@/commons/layout";
import { AuthGuard } from "@/commons/providers/auth/auth.guard";
import { AuthProvider } from "@/commons/providers/auth/auth.provider";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { NextThemesProvider } from "@/commons/providers/next-themes/next-themes.provider";
import { ReactQueryProvider } from "@/commons/providers/react-query/react-query.provider";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextThemesProvider>
          <AuthProvider>
            <ReactQueryProvider>
              <ModalProvider>
                <AuthGuard>
                  <CommonsLayout>{children}</CommonsLayout>
                </AuthGuard>
              </ModalProvider>
            </ReactQueryProvider>
          </AuthProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
